//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamcheck
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JamCheckDB : DbContext
    {
        public JamCheckDB()
            : base("name=JamCheckDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomStaff> CustomStaffs { get; set; }
        public virtual DbSet<JamCheckStaff> JamCheckStaffs { get; set; }
        public virtual DbSet<BodyType> BodyTypes { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Parish> Parishes { get; set; }
        public virtual DbSet<Transtype> Transtypes { get; set; }
        public virtual DbSet<UsedCarDealer> UsedCarDealers { get; set; }
        public virtual DbSet<UsedCar> UsedCars { get; set; }
    }
}
