//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamcheck
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jampracticeEntities : DbContext
    {
        public jampracticeEntities()
            : base("name=jampracticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dealership> Dealerships { get; set; }
        public virtual DbSet<Fuel> Fuels { get; set; }
        public virtual DbSet<ImportFrom> ImportFroms { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<parish> parishes { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SteeringPosition> SteeringPositions { get; set; }
        public virtual DbSet<TransmissionType> TransmissionTypes { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<ViewDealership> ViewDealerships { get; set; }
        public virtual DbSet<ViewVehicle> ViewVehicles { get; set; }
    
        public virtual ObjectResult<AllVehicles_pr_Result> AllVehicles_pr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllVehicles_pr_Result>("AllVehicles_pr");
        }
    
        public virtual ObjectResult<VehiclesDetails_Result> VehiclesDetails(Nullable<int> index)
        {
            var indexParameter = index.HasValue ?
                new ObjectParameter("index", index) :
                new ObjectParameter("index", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VehiclesDetails_Result>("VehiclesDetails", indexParameter);
        }
    }
}
