//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamcheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedCar
    {
        public int id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Makeid { get; set; }
        public string Model { get; set; }
        public Nullable<int> Bodytpyeid { get; set; }
        public string chassisnum { get; set; }
        public string Transnum { get; set; }
        public Nullable<int> TransTypeid { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<int> DealerID { get; set; }
    
        public virtual BodyType BodyType { get; set; }
        public virtual Make Make { get; set; }
        public virtual Transtype Transtype { get; set; }
        public virtual UsedCarDealer UsedCarDealer { get; set; }
    }
}
