//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamcheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedCarDealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsedCarDealer()
        {
            this.UsedCars = new HashSet<UsedCar>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string Streetname { get; set; }
        public Nullable<int> ParishID { get; set; }
        public string Phone { get; set; }
    
        public virtual Parish Parish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedCar> UsedCars { get; set; }
    }
}
